version: '2'
services:
  mysql:
    image: mysql:5.6
    container_name: "cashtransactionsdb"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=2211141"
      - "MYSQL_DATABASE=cashtransactionsdb"
  mysqltest:
    image: mysql:5.6
    container_name: "cashtransactionsdbtest"
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=2211141"
      - "MYSQL_DATABASE=cashtransactionsdbtest"

  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

    depends_on:
      - mysql
      - mysqltest

