<?php
/**
 * Created by PhpStorm.
 * User: abdujabbor
 * Date: 6/22/18
 * Time: 4:41 PM
 */

namespace app\models;


use yii\base\Model;

class TransactionForm extends Model
{
    public $username;
    public $amount;


    public function rules()
    {
        return [
            [['username', 'amount'], 'required'],
            ['amount', 'integer', 'min' => 0],
            [['username'], 'string', 'min' => 6],
        ];
    }

    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }


}